name: matrix_sdk
description: An SDK written in Dart to connect to Matrix, the federated communication protocol.
homepage: https://pattle.dev/pattle/library/matrix-dart-sdk
repository: https://pattle.dev/pattle/library/matrix-dart-sdk
issue_tracker: https://pattle.dev/pattle/library/matrix-dart-sdk/issues
documentation:

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  meta: ^1.1.6
  http: ^0.12.0+4
  chopper: ^3.0.6
  ffi: ^0.1.3
  async: ^2.4.0
  synchronized: ^2.2.0
  collection: ^1.14.12
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  mime: ^0.9.6+3
  image: ^2.1.19
  pedantic: ^1.0.0

dev_dependencies:
  precise_pattle: ^1.0.5
  effective_dart: ^1.2.1
  test: ^1.0.0
  mockito: ^4.1.0
  build_runner: ^1.0.0
  chopper_generator: ^3.0.1
  dotenv: ^1.0.0
  moor_generator: ^3.0.0